import { AGENT_BY_KEY, AGENT_CATALOG, FREE_AGENT_KEYS } from "./catalog";
import { PLANS_WITH_ALL_AGENTS } from "../pricing";

// Which pre-built agents an organization may install: the free ones always, the rest once an
// agent_purchases row exists (written by VOIZO platform admins; no card checkout yet).

const db = async () => (await import("../supabaseServer")).supabaseService;

export async function unlockedAgentKeys(orgId: string): Promise<Set<string>> {
  const keys = new Set<string>(FREE_AGENT_KEYS);
  try {
    const client = await db();
    // Pro and Scale plans include every agent (src/lib/pricing.ts).
    const { data: org } = await client.from("organizations").select("plan").eq("id", orgId).maybeSingle();
    if (org && PLANS_WITH_ALL_AGENTS.has(org.plan as string)) return new Set(AGENT_CATALOG.map((a) => a.key));
    const { data } = await client.from("agent_purchases").select("agent_key").eq("org_id", orgId);
    for (const r of data ?? []) keys.add(r.agent_key as string);
  } catch {
    /* table missing (tenancy migration not applied) → free agents only */
  }
  return keys;
}

export async function canInstallAgent(orgId: string | null, key: string): Promise<boolean> {
  const agent = AGENT_BY_KEY[key];
  if (!agent) return false;
  if (agent.tier === "free") return true;
  if (!orgId) return false;
  return (await unlockedAgentKeys(orgId)).has(key);
}

/** Public URL of an agent's sample clip (generated by scripts/generate-agent-samples.mjs). */
export function sampleUrl(key: string): string | null {
  const base = process.env.NEXT_PUBLIC_SUPABASE_URL;
  return base ? `${base}/storage/v1/object/public/agent-samples/${key}.mp3` : null;
}
